version: '3'
services:
  frontend: 
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '8000:8000'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    