version: '3'
services:
  frontend: 
    build:
      context: ./ogo
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    