version: '3'
services:
  frontend: 
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./package.json:/user/src/app/package.json
      - ./frontend:/usr/src/app/src
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/usr/src/app/backend
    